--- #YAML:1.0
name:                Mail-DKIM
version:             0.25
abstract:            Signs/verifies Internet mail with DKIM/DomainKey signatures
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Crypt::OpenSSL::RSA:           0.22
    Digest::SHA:                   0
    Digest::SHA1:                  0
    Error:                         0
    Mail::Address:                 0
    MIME::Base64:                  0
    Net::DNS:                      0
    Test::Simple:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jason Long <jlong@messiah.edu>
