# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-DKIM
version:      0.32_6
version_from: 
installdirs:  site
requires:
    Crypt::OpenSSL::RSA:           0.24
    Digest::SHA:                   0
    Mail::Address:                 0
    MIME::Base64:                  0
    Net::DNS:                      0
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
